var emojis = {
"innocent face ":"ʘ‿ʘ"
,"reddit disapproval face ":"ಠ_ಠ"
,"table flip / flipping table ":"(╯°□°）╯︵ ┻━┻"
,"put the table back":"┬─┬﻿ ノ( ゜-゜ノ)"
,"tidy up / dust the table":"┬─┬⃰͡ (ᵔᵕᵔ͜ )"
,"double Flip / double angry":"┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻"
,"fisticuffs":"ლ(｀ー´ლ)"
,"cute bear ":"ʕ•ᴥ•ʔ"
,"squinting bear":"ʕᵔᴥᵔʔ"
,"GTFO Bear":"ʕ •`ᴥ•´ʔ"
,"cute face with big eyes ":"(｡◕‿◕｡)"
,"surprised / loudmouthed ":"（　ﾟДﾟ）"
,"shrug face  ":"¯_(ツ)_/¯"
,"meh":"¯(°_o)/¯"
,"feel perky  ":"(`･ω･´)"
,"angry face":"(╬ ಠ益ಠ)"
,"excited ":"☜(⌒▽⌒)☞"
,"running ":"ε=ε=ε=┌(;*´Д`)ﾉ"
,"happy face  ":"ヽ(´▽`)/"
,"basking in glory  ":"ヽ(´ー｀)ノ"
,"kitty emote":"ᵒᴥᵒ#"
,"fido":"V•ᴥ•V"
,"meow":"ฅ^•ﻌ•^ฅ"
,"cheers  ":"（ ^_^）o自自o（^_^ ）"
,"devious smile":"ಠ‿ಠ"
,"4chan emoticon  ":"( ͡° ͜ʖ ͡°)"
,"crying face ":"ಥ_ಥ"
,"breakdown":"ಥ﹏ಥ"
,"disagree":"٩◔̯◔۶"
,"flexing ":"ᕙ(⇀‸↼‶)ᕗ"
,"do you even lift bro?":"ᕦ(ò_óˇ)ᕤ"
,"kirby":"⊂(◉‿◉)つ"
,"tripping out  ":"q(❂‿❂)p"
,"discombobulated ":"⊙﹏⊙"
,"sad and confused  ":"¯_(⊙︿⊙)_/¯"
,"japanese lion face":"°‿‿°"
,"confused  ":"¿ⓧ_ⓧﮌ"
,"confused scratch":"(⊙.☉)7"
,"worried":"(´･_･`)"
,"dear god why  ":"щ（ﾟДﾟщ）"
,"staring ":"٩(๏_๏)۶"
,"pretty eyes":"ఠ_ఠ"
,"strut":"ᕕ( ᐛ )ᕗ"
,"zoned":"(⊙_◎)"
,"crazy":"ミ●﹏☉ミ"
,"trolling":"༼∵༽ ༼⍨༽ ༼⍢༽ ༼⍤༽"
,"angry troll":"ヽ༼ ಠ益ಠ ༽ﾉ"
,"fuck it":"t(-_-t)"
,"sad face":"(ಥ⌣ಥ)"
,"hugger":"(づ￣ ³￣)づ"
,"stranger danger":"(づ｡◕‿‿◕｡)づ"
,"flip friend":"(ノಠ ∩ಠ)ノ彡( o°o)\\"
,"cry face":"｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡"
,"cry troll":"༼ ༎ຶ ෴ ༎ຶ༽"
,"TGIF":"“ヽ(´▽｀)ノ”"
,"dancing ":"┌(ㆆ㉨ㆆ)ʃ"
,"sleepy":"눈_눈"
,"angry birds":"( ఠൠఠ )ﾉ"
,"no support ":"乁( ◔ ౪◔)「      ┑(￣Д ￣)┍"
,"shy ":"(๑•́ ₃ •̀๑) "
,"fly away":"⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾"
,"careless":"◔_◔"
,"love":"-`ღ´-"
,"Touchy Feely":"ԅ(≖‿≖ԅ)"
,"Kissing":"( ˘ ³˘)♥ "
,"shark face / jagged mustache":"( ˇ෴ˇ )"
,"emo dance ":"ヾ(-_- )ゞ"
,"dance ":"♪♪ ヽ(ˇ∀ˇ )ゞ"
,"opera":"ヾ(´〇`)ﾉ♪♪♪"
,"winnie the pooh":"ʕ •́؈•̀)"
,"boxing":"ლ(•́•́ლ)"
,"fight":"(ง'̀-'́)ง"
,"listening to headphones":"◖ᵔᴥᵔ◗ ♪ ♫ "
,"robot":"{•̃_•̃}"
,"seal":"(ᵔᴥᵔ)"
,"questionable / dislike":"(Ծ‸ Ծ)"
,"Winning!":"(•̀ᴗ•́)و ̑̑"
,"Zombie":"[¬º-°]¬"
,"pointing":"(☞ﾟヮﾟ)☞"
,"chasing / running away":"''⌐(ಠ۾ಠ)¬'''"
,"whistling / music":"(っ•́｡•́)♪♬"
,"injured":"(҂◡_◡) "
,"creeper":"ƪ(ړײ)‎ƪ​​"
,"eye roll":"⥀.⥀"
,"flying":"ح˚௰˚づ "
,"things that can't be unseen":"♨_♨"
,"looking down":"(._.)"
,"im a hugger":"(⊃｡•́‿•̀｡)⊃"
,"wizard":"(∩｀-´)⊃━☆ﾟ.*･｡ﾟ"
,"yum":"(っ˘ڡ˘ς)"
,"judging":"( ఠ ͟ʖ ఠ)"
,"tired / older":"( ͡ಠ ʖ̯ ͡ಠ)"
,"dislike / depressed":"( ಠ ʖ̯ ಠ)"
,"hitchhiking":"(งツ)ว"
,"satisfied":"(◠﹏◠)"
,"sad and crying":"(ᵟຶ︵ ᵟຶ)"
,"stunna shades":"(っ▀¯▀)つ"
,"chicken":"ʚ(•｀"
,"barf":"(´ж｀ς)"
,"fuck off":"(° ͜ʖ͡°)╭∩╮"
,"smiley toast":"ʕʘ̅͜ʘ̅ʔ"
,"exorcism":"ح(•̀ж•́)ง † "
,"taking a dump / straining":"(⩾﹏⩽)"
,"dab":"ヽ( •_)ᕗ"
,"Wave Dance":"~(^-^)~"
,"Happy Hug":"(ᵔᵕᵔ)/"
};